using System;
using System.Collections.Generic;
using System.Numerics;
using PicoGK;
using Leap71.ShapeKernel;
using MyFirstApp.Core;
using MyFirstApp.Core.Engine;

namespace MyFirstApp.Algorithms.Playground
{
    public class ImplicitGenusGyroid : EngineeringComponent
    {
        // ==========================================
        // 1. PARAMETERS
        // ==========================================
        // These variables will hold the current state of our component's parameters.
        // They are controlled by the sliders and UI generated by GetComponentParameters().
        private float m_fGenusGap           = 0.3f;
        private float m_fBoundingBoxExtent  = 2.5f;
        private float m_fGyroidUnitSize     = 1.0f;
        private float m_fGyroidThickness    = 0.5f;

        // This will hold the transparent preview shape so we can draw it later.
        private Voxels? m_voxPreviewGenus   = null;


        // ==========================================
        // 2. PARAMETER HANDLING (The UI)
        // ==========================================
        // This method defines the sliders that will appear in the UI.
        protected override List<Parameter> GetComponentParameters()
        {
            return new List<Parameter>
            {
                new Parameter
                {
                    Name = "Genus Gap",
                    Value = m_fGenusGap,
                    Min = 0.1f,
                    Max = 1.0f,
                    OnChange = (val) => m_fGenusGap = val
                },
                new Parameter
                {
                    Name = "Size (Extent)",
                    Value = m_fBoundingBoxExtent,
                    Min = 1.0f,
                    Max = 5.0f,
                    OnChange = (val) => m_fBoundingBoxExtent = val
                },
                new Parameter
                {
                    Name = "Gyroid Unit Size",
                    Value = m_fGyroidUnitSize,
                    Min = 0.2f,
                    Max = 3.0f,
                    OnChange = (val) => m_fGyroidUnitSize = val
                },
                new Parameter
                {
                    Name = "Gyroid Thickness",
                    Value = m_fGyroidThickness,
                    Min = 0.1f,
                    Max = 0.9f,
                    OnChange = (val) => m_fGyroidThickness = val
                }
            };
        }


        // ==========================================
        // 3. LIFECYCLE: PREVIEW
        // ==========================================
        // This runs every frame and is for drawing non-solid, temporary helpers.
        public override void OnPreview(EngineeringContext ctx)
        {
            // If we have generated the preview shape, draw it transparently.
            if (m_voxPreviewGenus != null)
            {
                // This is Step 5 from the original example, but done correctly
                // in the preview stage so it doesn't become part of the final model.
                Sh.PreviewVoxels(m_voxPreviewGenus, Cp.clrRandom(), 0.5f);
            }
        }


        // ==========================================
        // 4. LIFECYCLE: CONSTRUCTION
        // ==========================================
        // This is the core logic. It only runs when a parameter changes (because of the
        // caching system). It does the "heavy lifting" of creating the solid model.
        protected override void OnConstruct(EngineeringContext ctx)
        {
            // Note: Use voxel size 0.01mm for good resolution in the main app settings.

            // Step 1: Generate SDF (Signed Distance Field) for the Genus shape.
            // We use our class parameter m_fGenusGap, which is controlled by the UI slider.
            IImplicit sdfGenus = new ImplicitGenus(m_fGenusGap);

            // Step 2: Define the bounding object for the Genus.
            // We use m_fBoundingBoxExtent from our UI slider.
            BBox3 oBBox = new BBox3(
                1.2f * new Vector3(-m_fBoundingBoxExtent, -m_fBoundingBoxExtent, -m_fBoundingBoxExtent + 1.5f), 
                1.2f * new Vector3(m_fBoundingBoxExtent, m_fBoundingBoxExtent, m_fBoundingBoxExtent - 1.5f));

            // Step 3: Render the implicit shape into a solid Voxel object.
            // This is the outer shell of our final part.
            Voxels voxGenus = new Voxels(sdfGenus, oBBox);

            // Store a copy of this shape so our OnPreview() method can draw it.
            m_voxPreviewGenus = voxGenus.voxDuplicate();

            // Step 4: Create the Gyroid pattern and intersect it with the Genus solid.
            // We use our Gyroid parameters from the UI sliders.
            IImplicit sdfPattern = new ImplicitGyroid(m_fGyroidUnitSize, m_fGyroidThickness);
            Voxels voxGyroidGenus = voxGenus.voxIntersectImplicit(sdfPattern);

            // Step 5: Add the final, constructed solid to the main assembly.
            // The framework will automatically cache this result.
            // The solid part of the visualization from the original example is done here.
            ctx.Assembly.BoolAdd(voxGyroidGenus);
        }
    }
}